name: zena
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - anyio
  - appdirs
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - attrs
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - blas=1.0=openblas
  - bleach
  - bottleneck
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - ca-certificates
  - cached-property
  - cached_property
  - certifi
  - cffi
  - charset-normalizer
  - click
  - comm
  - contourpy
  - cycler
  - cyrus-sasl
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - et_xmlfile
  - exceptiongroup
  - executing
  - expat
  - fonttools
  - fqdn
  - freetype
  - h2
  - hpack
  - html5lib
  - hyperframe
  - icu
  - idna
  - importlib_resources
  - ipykernel
  - ipython
  - ipython_genutils
  - isoduration
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab_pygments
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libdeflate
  - libedit
  - libexpat
  - libffi
  - libiconv
  - libpng
  - libpq
  - libsodium
  - libsqlite
  - libtiff
  - libwebp-base
  - libxml2
  - libxslt
  - libzlib
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - nbclassic
  - nbclient
  - nbformat
  - ncurses
  - nest-asyncio
  - notebook-shim
  - numexpr
  - openjpeg
  - openldap
  - openpyxl
  - openssl
  - overrides
  - packaging
  - pandas
  - parso
  - patsy
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkgutil-resolve-name
  - platformdirs
  - prompt-toolkit
  - prompt_toolkit
  - psycopg2
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyparsing
  - pysocks
  - python-dateutil
  - python-dotenv
  - python-json-logger
  - python-tzdata
  - python_abi=3.12
  - pytz
  - pyyaml
  - pyzmq
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rpds-py
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - six
  - sniffio
  - sqlite
  - stack_data
  - statsmodels
  - terminado
  - threadpoolctl
  - tinycss2
  - tk
  - tornado
  - traitlets
  - types-python-dateutil
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzdata
  - unicodedata2
  - uri-template
  - urllib3
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - wquantiles
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstandard
  - zstd
  - pip:
      - babel==2.16.0
      - backtrader==1.9.78.123
      - fastjsonschema==2.21.1
      - frozendict==2.4.6
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - json5==0.10.0
      - jsonpointer==3.0.0
      - lxml==4.9.4
      - mistune==3.1.0
      - multitasking==0.0.11
      - nbconvert==7.16.5
      - numpy==2.2.3
      - pandocfilters==1.5.1
      - peewee==3.17.8
      - prometheus-client==0.21.1
      - psutil==6.1.1
      - requests-futures==1.0.2
      - soupsieve==2.6
      - tqdm==4.67.1
      - yahooquery==2.3.7
      - yfinance==0.2.54